version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: postgres_docker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb


  spring-app:
    build: 
      dockerfile: dockerfileServer
    container_name: my-spring-app
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devdb
      SPRING_DATASOURCE_USERNAME: devuser
      SPRING_DATASOURCE_PASSWORD: devpassword
    depends_on:
      - postgres